name: Run Blog Creator Regularly

on:
  schedule:
    # Runs every 10 minutes
    - cron: '*/10 * * * *' 
  workflow_dispatch: # Allows you to manually trigger the workflow from the GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest # Uses a Linux virtual machine

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Action to check out your repository code

    - name: Set up Python
      uses: actions/setup-python@v5 # Action to set up Python environment
      with:
        python-version: '3.9' # Specify a compatible Python version (e.g., '3.10', '3.11')

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Install libraries from requirements.txt

    - name: Run Python script
      env:
        GNEWS_API_KEY: ${{ secrets.GNEWS_API_KEY }} # Access API key from GitHub Secrets
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }} # Access API key from GitHub Secrets
        # Uncomment and set if you use a logo and it's in your repo root:
        # BRANDING_LOGO_PATH: 'my_logo.png' 
      run: |
        python main.py # Execute your Python script

    # This step uploads the generated files so you can download them later.
    - name: Upload Generated Blogs and Images
      uses: actions/upload-artifact@v4
      with:
        name: generated-blogs-and-images-${{ github.run_id }}
        path: |
          blog_drafts/
          transformed_images/